### ISSUE TITLE
Publication Author List

### ISSUE THREAD

**Issue by ankur92** [aminmkhan/Awesome-CV#10]
Hi, 

I am trying to limit the number of author names which are printed in the list to just 1. I tried to include
	maxnames=1,
	maxcitenames=1, % affects only the citations in the document body
in the cls file but it didn't change it. Any suggestions? 

Thank you.

**Comment by aminmkhan** [comment]
You can try with different `biblatex` settings, or alternatively just manually update the `bib` file.
