### ISSUE TITLE
Bibtex list adding an extra "." before the numericlabel

### ISSUE THREAD

**Issue by mzaman11** [aminmkhan/Awesome-CV#5]
Hello, 
I have updated the awesome-cv.cls file and added the "Bibliography" section in the file. In the "style" option, instead of using "verbose", I am using "numeric" option which lists the publication with numeric label.
 ```
\RequirePackage[ % BibLaTeX
	sorting=ydnt, % Sorts entries by year (descending order), name, title
	style=numeric,
	labelnumber=true,
	doi=false,
	isbn=true,
	url=false,
	eprint=false,
	backref = false, % include back references in bibliography
	maxcitenames=3, % affects only the citations in the document body
	maxbibnames=99, % affects only the bibliography, pass 99 to print all
	hyperref=true,
	block=space,
	backend=biber % {Options: bibtex, biber}
	]{biblatex}
``` 

The problem is, for some reason, this change adds an extra "." from the second item in the list when I use \printbibliography command:
```
\cvsection{Publications}
\nocite{*}
\printbibliography[type=inproceedings,heading=subbibliography,title={Conference proceedings}]
```

Here is the result:
```
Conference proceedings
[1] ABC
     A.B, A.C, C.A
     Conferece A, 2018
. [2] XYZ
      Y.Z, A.B, M.K
      Another Conferece, 2018
. [3] CYZ
      Some, Authors
      Differenct Conference, 2017
```

I can't figure out why is there an extra "." appended in the pdf?

**Comment by aminmkhan** [comment]
@mzaman11 This could be caused by the [custom code](https://github.com/aminmkhan/Awesome-CV/blob/feature/publications/awesome-cv.cls#L732-L836) handling formatting of bib entries. You can either dig further into above code for numbered list, or comment it out to have a list of publications without customizations.

**Comment by alchem0x2A** [comment]
It seems that there is an extra `\newunit` at the end of each `\DeclareBibliographyDriver` definitions. Remove it works in my case

**Comment by aminmkhan** [comment]
Also see https://github.com/posquit0/Awesome-CV/pull/23#issuecomment-556185812 for a proposed fix.
